server:
  port: 6001

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka
  instance:
    instance-id: admin-server-6001
    prefer-ip-address: true

spring:
  application:
    name: admin-server
  zipkin:
    base-url: http://localhost:9411

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: ["health","info"]
