server:
  port: 9411

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka
  instance:
    instance-id: zipkin-9411
    prefer-ip-address: true

spring:
  application:
    name: zipkin

management:
  metrics:
    web:
      server:
        auto-time-requests: false
