server:
  port: 8802

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka
  instance:
    instance-id: service-redis-8802
    prefer-ip-address: true

spring:
  application:
    name: service-redis
  zipkin:
    base-url: http://localhost:9411
  redis:
    host: 192.168.101.49
    port: 6379
    jedis:
      pool:
        max-active: 200
        max-wait: -1ms
        max-idle: 10
        min-idle: 0
    timeout: 1000ms