server:
  port: 8801

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka
  instance:
    instance-id: service-user-8001
    prefer-ip-address: true

spring:
  application:
    name: service-user