server:
  port: 8801

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka
  instance:
    instance-id: service-user-8801
    prefer-ip-address: true

spring:
  application:
    name: service-user
  zipkin:
    base-url: http://localhost:9411