spring:
  application:
    name: config
  #验证方式：http://localhost:8888/${ymlName}(上传的yml文件的名称)/master(label)
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/woohaifeng/template-cloud.git
          search-paths: repository
          username: 326734854@qq.com
          password: 098614.Github
  zipkin:
    base-url: http://localhost:9411

#cloud-cofing端口默认必须是8888，如果要修改端口，必须使用bootstrap.yml
server:
  port: 8888

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka
  instance:
    instance-id: config-8888
    prefer-ip-address: true
